## Results

We would like to briefly discuss the results of our work.

### The code

Most of the code exists in the `cpu` package and consists of around 4500 source lines of code (SLoC) including comments and blank lines.
Some of the provided skeleton-code exists in the `system` package and makes up a few hundred lines of code.

### Performance

In the best of circumstances, -- with address translation disabled, IPIs disabled, no preemption,  -- cores are able to execute around 65 million instructions per second (mips) on an Intel Core i7 1065G7.
This number decreases when additional features are added.
Performance penalties are approximately as follows:

- 20% for address translation, and
- 15% for enabling IPIs (checked every cycle) and approximately 5% for each added core.

These are the largest performance penalties because of how they affect the fetch-execute cycle.
Address translation requires lookup in a map, and IPIs require atomic loads to occur on every cycle.
After enabling both, we are still left with adequate performance to do useful work and run realistic example programs.

However, if performance is not to our liking, we can mitigate most of the performance penalty of IPIs by only checking them every *K* cycles.
This ensures that IPIs can still be received within microseconds and reduces the frequent atomic loads to a frequently accessed local counter and infrequent loads and stores.

The overhead of address translation is difficult to negate, but we accept it as necessary.

With all features enabled and mitigation applied, the emulator is still able to execute at close to 50 million instructions per second, if not more.
We find this to be adequate for any purpose that Gotos can be useful for and leaves enough margin to add other performance-degrading features without much worry.

### Code quality

While we are satisfied with the core functionality provided, and the modularity is adequate for our purposes, foresight tells us that more modularity is desired within the `cpu` package.

As mentioned in section \@ref(sec:assignment-iii), we could add a `Translator` interface for easily switching the memory virtualisation method used.
Additionally, we could add a `Cacher` interface to modularise cache implementations.
However, for such core functionality, the pointer-chasing that ensues from generalising the interfaces might come with a penalty to performance.
This requires more work.

The code is still quite "researchy" -- for lack of a better adjective -- and could do with review by more people and some rewriting and proper documentation before it is ready for real-world usage.
We have tried to follow practices that we believe to be generally sound, such as:

- panic as early as possible on API misuse,
- aliased types to prevent said API misuse, and
- descriptive names.

Still, we do not proclaim ourselves to be experts by any stretch of the imagination and Gotos is far from finished.
