## Future work

There are multiple improvements to be done for this project and many features to be added before widespread adoption can occur, but we believe that Gotos has a real potential to be an extensible and user-friendly platform for teaching all things OS.

### Modularise core functionality

There are several opportunities for providing modularity in the `cpu` package.
While we would like to provide better code separation and modularity, the development speed would likely be severly inhibited if we were to make every internal interface a dynamic interface.

This does not mean we should not eventually modularise the code.
Modularity could add multiple benefits:

- We can add "debug hooks" for functions to do logging or track metrics.
  This functionality should likely sit behind a `debugHooksEnable` configuration flag as it might severely impact performance.
  Still, there is much performance left and we should not be too afraid of slightly reducing it if it leads to better code quality and easier development and testing.

- Similarly, we can add hooks for things such as testing, interjection, etc.
  This could simplify automatic testing for student-submitted code as we could expose one implementation of an interface when students are developing, then use a special, secret implementation in testing or add hooks at certain points in the execution pipeline.

Being able to easily swap certain functionality for others is a powerful concept and improves development, testing, debugging, and much, much more.

### Interrupt controller

The implementation of interrupts -- though adequate for the current assignments -- could use some work.
Current implementation uses what we would call "special purpose" interfaces.
An interrupt controller would serve as a more general interface and could make use of the intended control status registers to signal interrupts in a way that is closer to the

### Compliant floating-point numbers

Although a very minor detail, it would be nice to have a fully compliant implementation from the application/user-mode perspective.
The current implementation is built for speed and simplicity and does not fully comply with the RISC-V specification for how floating-point numbers should behave.

Go has `math/big` which contains most of the functionality required, such as rounding modes, adjustable accuracy, etc.
It should be possible to create a fully compliant solution, although it is guaranteed to be much slower than current implementation.

### Extensive testing and benchmarking

In somewhat of the same sentiment as the previous point: all parts of Gotos should be double and triple-checked against the relevant specifications and adequate tests should be written to enable rapid development without fear of introducing subtle bugs.

Most of the focus throughout this project has been to create a working prototype and Gotos is far from finished.
Tests can be written for all instructions as RISC-V is unlikely to change in the near future.
However, it is more difficult to test the rest of Gotos as different components are subject to rapid change and iteration.

### MMIO and other devices

Current implementation has no memory mapped IO and the IO architecture is simplistic.
We believe it is possible to wrap `Memory` in an interface that allows a system to define a full system of memory-mapped devices such as UART, a frame-buffer, and much-much more.

Because these devices would share the address space with normal memory, they could be mapped directly to user-space processes which both improves performance, and extends the capabilities of the system.
This is similar to the point about generally modular code.

Before this can happen though, physical memory protection (PMP) and physical memory attributes (PMA) (see section \@ref(sec:mem-virt)) should be supported and the memory controller should be improved to take these features into account when deciding whether or not to cache accesses.

### Nicer visualisation and debugging

A visualiser would be a nice quality-of-life improvement, especially when stepping through programs.
The best alternative that is currently available is `StepAndDump` which is best used with only one core, and integrates poorly with the terminal, easily flooding it with printouts.

The debugging experience can also be much improved with functions like `StepBack` and the likes, allowing us to step backwards and replay certain events.
Building this as a naive collection of old copies of the system is possible, though very wasteful.

All this should be wrapped in a nice command-line interface or perhaps even a graphical interface.

This might be suitable as a bachelor's or master's project.

### Properly defined system

An advantage of Gotos is that it is bare-bones so that most anything can be built with it.
A disadvantage of Gotos is that it is bare-bones so that most everything has to be built for it to work.

Our approach to developing Gotos presents both strengths and weaknesses.
However, we believe that we can properly define the system interface to provide better interoperability, while still keeping the bare-bones, "from scratch" experience of building an operating system using Gotos.

This process would involve much experimentation as well as input from experts of the field; with the goal of crafting a specification that is flexible and extensible, yet still provides a target for how a system is expected to behave.

A properly defined system interface would allow development of a C standard library, which we expect could cut down on the effort required to integrate Gotos into more advanced OS development courses.

It should be possible to also provide a bare-bones system which conforms to these specifications as is done in Nachos. @nachos-report
However, we believe that starting from the most basic level, and only providing helpful components when necessary is a better approach to utilising Gotos.

### Better lab-assignments

We have no real experience teaching operating systems, only learning about them.
The proposed assignments are likely to be of sub-par quality.
We believe the assignments require heavy iteration and proper coordination with the course lecturer if they are to provide good learning outcomes and incorporate with the curriculum of the course.

As mentioned, we have not made a proper effort to create perfect assignments.
We believe that while crafting better assignments is a core goal of the project, this project is already large enough that we believe the additional burden of creating assignments would detract from the quality of Gotos.

We believe that a wide variety of assignments can use Gotos as a solid foundation for teaching operating systems.
