## Executing instructions

Most processors have a fetch-execute cycle, a general flow that instructions follow through the processor; our emulator is no different.
Cores can be in three general states: *running*, *halted*, and *stopped*.

When a core is running, it is actively fetching and executing instructions.
When a core is halted, it sleeps most of the time, waking up to periodically check interrupts.
When a core is stopped, it has no associated goroutine and only exists as a struct.
In the stopped state, a core can safely be started using `c.Start()`.

### System setup

While the main contribution of this thesis is the multicore RISC-V-emulator, we will approach explaining the core execution loop starting from an implementation of the `System` interface.
We do this because a core expects a `System` interface if it is to even operate.
In listing\ \@ref(lst:minimal-system) we define a minimal system that fulfills the `cpu.System` interface.

```{.go #lst:minimal-system caption="Our minimal system implementation." float=!ht}
// in package system
type System struct {
    core cpu.Core

    // --- cpu.System interface ---
    memory     cpu.Memory
    rsets      cpu.ReservationSets
    interrupts cpu.InterruptMatrix
    wgAwake    sync.WaitGroup
    wgRunning  sync.WaitGroup
}

// Methods for shared resources in cpu.System interface
func (s *System) Memory() *cpu.Memory { return &s.memory }
func (s *System) WgAwake() *sync.WaitGroup { return &s.wgAwake }
func (s *System) WgRunning() *sync.WaitGroup { return &s.wgRunning }

func (s *System) ReservationSets() *cpu.ReservationSets {
    return &s.rsets
}

func (s *System) InterruptMatrix() *cpu.InterruptMatrix {
    return &s.interrupts
}

// Methods for handlers in cpu.System interface
func (s *System) HandleTrap(c *cpu.Core) { c.Halt() }
func (s *System) HandleBoot(c *cpu.Core) { }
```

Some functions in this listing are unexplained such as `c.Halt()`; we explain these later.
There are a few steps to creating a new system so we have created a function that streamlines the process for making a system with a single core in listing\ \@ref(lst:newsystem):
This function is only an example of how it can be done.

```{.go #lst:newsystem caption="Creating a new system." float=!ht}
// in package system
func NewSystem() *System {
    sys = &System {
        memory: cpu.NewMemory(),
        rsets:  cpu.NewReservationSets(),
    }

    sys.core = cpu.NewCore(0, sys)

    return sys
}
```

This function first creates a system with the required shared resources (the `sync.WaitGroup`s are created implicitly so we don't need to do it in the code), then we create a core with ID set to 0 and we pass the system we just created as the second argument.

### System startup

System startup is as simple as `s.Start()` which is implemented as shown in listing\ \@ref(lst:systemstart).

```{.go #lst:systemstart caption="Creating a new system." float=!ht}
// in package system
func (s *System) Start() {
    s.core.Start()
}
```

The function iterates over each core in the system and calls its `Start()` function.

#### Core startup {#impl:startup}

Core startup is slightly more complicated, but it starts with the simple function `c.Start()` as shown in listing\ \@ref(lst:corestart).

```{.go #lst:corestart caption="Starting a single core." float=!ht}
// in package cpu
func (c *Core) Start() {
    c.system.WgAwake().Add(1)
    c.system.WgRunning().Add(1)
    go c.run()
}
```

The function simply registers that this core is awake and running before it spawns a goroutine (lightweight thread) that does all the heavy lifting.

`c.run()` is yet more complicated, shown in listing\ \@ref(lst:corerun).

```{.go #lst:corerun caption="The main loop" float=!ht}
// in package cpu
func (c *Core) run() {
    // register that this core is no longer receiving interrupts
    // when this function returns
    defer c.system.WgAwake().Done()

    // prevent the core running in multiple goroutines
    c.bcm.Lock()
    defer c.bcm.Unlock()

    c.state = coreStateRunning
    c.Boot()

    for {
        if c.state == coreStateStopping {
            c.state = coreStateStopped
            break
        }
        c.Step()
    }
}
```

#### Core boot: Boot()

Before a core starts running any code at all, it runs the boot-handler.
When returning from the boot-handler, the processor starts executing in user-mode.
This is wrapped in the function `Boot()`, shown in listing\ \@ref(lst:boot).

```{.go #lst:boot caption="The Boot function in Gotos" float=!ht}
// in package cpu
func (c *Core) Boot() {
    c.system.HandleBoot(c)
    c.pc = c.csr[Csr_MEPC]
}
```

The first line is obvious; it calls the boot-handler defined by the system.

The second line assigns the value from the **\gls{mepc}** \acrshort{csr} to the program counter.
This is done as a side-effect of the implicit `mret`-instruction that is executed when entering user-mode/leaving machine-mode (see section\ \@ref(arch:trap)).

### Step()

`Step()` is the main part of the execution-loop.
It does a couple things:

(1) if the core is sleeping; check external interrupts; sleep for a bit before returning; `Step()` does no more work in this case, then
(1) check timers/counters (internal interrupts), then
(1) check external interrupts, then
(1) if all the above went without exceptions; load the instruction from memory; return if it fails, then
(1) execute the instruction, and finally
(1) update the program counter.

#### Checking counters and interrupts

In `Step()`, checking counters is implemented as in listing\ \@ref(lst:checkcounter).

```{.go #lst:checkcounter caption="Checking counters inside Step()." float=!ht}
// in package cpu
// inside function Step
if c.counter.enable {                     // (1)
    if c.counter.value == 0 {             // (2)
        c.counter.enable = false          // (3)
        c.trap(TrapMachineTimerInterrupt) // |-|
        return                            // |-|
    }
    c.counter.value -= 1                  // (4)
}
```

This does a few things: (1) check if the internal counter is active, and if so (2) check if the counter has reached 0, and if so (3) disable the counter, cause a trap with an appropriate exception code, and return, otherwise (4) simply decrement the value of the counter.

Similarly, checking external interrupts is shown in listing\ \@ref(lst:stepcheckinterrupt).

```{.go #lst:stepcheckinterrupt caption="Checking external interrupts inside Step()." float=!ht}
// cpu/core.go
// inside function Step
c.interruptCounter++
if c.interruptCounter >= 100 {
    c.interruptCounter = 0
    if c.checkInterrupts() {
        return
    }
}
```

A counter is associated with this process so that cores do not check external interrupts every cycle.
The `checkInterrupts()` function is costly (see section\ \@ref(impl:ipi)) and by only checking it every few cycles, we negate most of that cost.

#### Instruction fetch, decode, and execute

The final part of the `Step()` function is shown in listing\ \@ref(lst:stepexecute).

```{.go #lst:stepexecute caption="Fetching and executing the instruction located at the address given by program counter." float=!ht}
// cpu/core.go
// inside function Step
success, inst := c.loadInstruction(c.pc)
if !success {
    return
}

c.execute(inst)

if !c.jumped {
    c.pc += 4
}
```

First, the `loadInstruction()` does as its name says; it attempts to load an instruction from the (possibly virtual) address given by the program counter `c.pc`.
If this loading fails, the function causes a trap and returns `false, 0`.
Otherwise, if loading succeeds, it returns `true, inst`, where `inst` is a 32-bit unsigned integer that represents a RISC-V instruction.

If successful, the instruction is passed to `execute()` which will decode the instruction based on the format specified in the non-privileged specification\ [@rv5vol1, chapter 24].
Execution may cause the `c.jumped` flag to be set.
In this case, the program counter will not be incremented.

Decoding is implemented as a tree of `switch...case` statements as shown in listing\ \@ref(lst:decode).
The definitions of the capitalised constants are left out for brevity.

```{.go #lst:decode caption="Decoding the 32-bit instruction encoding step-by-step. This is a small excerpt of the only function in the file. The function is 695 lines of this pattern." float=!ht}
// cpu/execute.go
// inside function execute
opcode := inst & 0x7f
switch opcode {
case OP:
    funct7 := (inst >> 25) & 0x7f
    switch funct7 {
    case OP_A:
        funct3 := (inst >> 12) & 0x7
        switch funct3 {
        case ADD:
            c.add(inst)
        case SLL:
            c.sll(inst)
        // ...
        }
    }
case OP_IMM:
    funct3 := (inst >> 12) & 0x7
    case ADDI:
        c.addi(inst)
    // ...
// ...
}
```

Note how the value of `inst` is passed to the actual instruction such as in `c.add(inst)`.
We could have made each instruction avoid parsing arguments themselves and instead write each instruction so that it would take arguments such as `rs1`, `rs2`, and `imm`.
We decided against this however, as it made the code difficult to follow.
Preserving the value of `inst` through the entire process makes it easier to implement every instruction as an isolated unit.

Instructions are implemented across files depending on which RISC-V extension they come from (see section\ \@ref(arch:isa)).
There are `r 40+15+26+26+8+6+1` instructions implemented across seven files.
The files are `cpu/rv32i.go`, `cpu/rv32a.go`, `cpu/rv32d.go`, `cpu/rv32f.go`, `cpu/rv32m.go`, `cpu/zicsr.go`, and `cpu/zifencei.go`.

As an example, we have included the implementation of `xori()` (xor immediate) in listing\ \@ref(lst:xori).

```{.go #lst:xori caption="xori is a simple instruction and is easy to implement." float=!ht}
// cpu/rv32i.go
// xor immediate
func (c *Core) xori(inst uint32) {
    rd := (inst >> 7) & 0x1f
    rs1 := (inst >> 15) & 0x1f
    imm11_0 := uint32(int32(inst) >> 20)
    c.reg[rd] = c.reg[rs1] ^ imm11_0
}
```

Most instructions follow this pattern.
Some instructions will occasionally check other registers, perform special actions, or raise exceptions/traps (see section\ \@ref(impl:atomics)).
This concludes the core loop of the emulator.

### Control flow

Control-flow instructions are those which conditionally, or unconditionally interact with the program counter.
An example of such an instruction is `beq` (branch equal, see listing\ \@ref(lst:beq)) which performs a relative jump if the values of two registers match.

```{.go #lst:beq caption="beq jumps to an address if two registers contain equal values. If the target address is not aligned on a 4-byte (instruction) boundary, the emulator raises a trap." float=!ht}
// cpu/rv32i.go
// branch equal
func (c *Core) beq(inst uint32) {
    // decode logic ...
    targetAddress := c.pc + offset
    if c.reg[rs1] == c.reg[rs2] {
        if targetAddress&0x3 != 0 {
            c.csr[Csr_MTVAL] = targetAddress
            c.trap(TrapInstructionAddressMisaligned)
            return
        }
        c.pc = targetAddress
        c.jumped = true
    }
}
```

Here, the **mtval** CSR is used to relay critical information about the failing instruction so that the operating system may properly deal with the trap.

### Traps

On the topic of traps, from the `cpu`-side, they are simple.
The most common trap-reason for a program should be that it has executed an `ecall`-instruction.
This is a **system** instruction, implemented in a very simple manner, shown in listing\ \@ref(lst:ecall).

```{.go #lst:ecall caption="ecall intentionally causes a trap with a special code." float=!ht}
// cpu/rv32i.go
// environment call
func (c *Core) ecall(inst uint32) {
    c.trap(TrapEcallUMode)
    return
}

// cpu/trap.go
func (c *Core) trap(reason uint32) {
    c.csr[Csr_MCAUSE] = reason
    c.csr[Csr_MEPC] = c.pc
    c.jumped = true
    c.system.HandleTrap(c)
    c.pc = c.csr[Csr_MEPC] // implicit mret
}
```

The `trap()` function handles most of this instruction for us in this case.
Other instructions may require additional setup (usually just assigning the proper value to **mtval**) before raising a trap.

`trap()` sets the `c.jumped` flag so that the processor does not increment the program counter automatically.
We do this because neither the instructions, nor the `execute()` function, return any success- or error-value which we can propagate.
A trap can be treated as a jump for all intents and purposes.

### Loads and stores

Load and store instructions interface with memory through the memory controller.
The memory controller is explained in greater detail in section\ \@ref(impl:mc).
An example of a load is given in listing\ \@ref(lst:lw).

```{.go #lst:lw caption="lw loads a word from memory into register rd." float=!ht}
// load word
func (c *Core) lw(inst uint32) {
    // decode logic ...
    if success, w := c.loadWord(address); success {
        c.reg[rd] = w
    }
}
```

`loadWord()` is defined in `cpu/memory_controller.go` and is a wrapper for the more general `load()` function defined in the same file.

### Halting

Halting the processor is simple.
By setting `c.state = coreStateNopLoop`, the core will enter a no-operation loop where it only checks interrupts and sleeps.
`Halt()`, shown in listing\ \@ref(lst:halt), does this, but also checks what the current state of the core is, and if it is running, it signals that it is no longer actively executing.

```{.go #lst:halt caption="Halting in Gotos is simple enough." float=!ht}
// cpu/core.go
func (c *Core) Halt() {
    if c.state == coreStateRunning {
        c.system.WgRunning().Done()
        c.state = coreStateNopLoop
        return true
    }
    return false
}
```

### Stopping the system

Recall that the `run()` function introduced in section\ \@ref(impl:startup) checks the state of the processor in every cycle, and if the core state changes to *stopping*, the core will signal it is ending and it will break out of the loop.

Once all cores in the system have signalled they have stopped, the system can safely exit.
However, the mechanism for initiating a core to stop is contrived.
While we could likely include a `Stop()` function that both halts, then stops the core, we have not done so.

Instead, what we do is allow the system to send an interrupt with a special code, telling the core to shut down.
When all cores have been informed to shut down, the system can wait on `s.wgAwake` to ensure all cores are in fact shut down before returning.

### System run

`Run()` is a shorthand function that (1) starts all cores, (2) waits for all cores to halt, (3) sends a stop-signal to all cores, and (4) waits for all cores to stop.
Waiting for all cores to halt done by waiting on `s.wgRunning`.
The stop-signal is sent by raising an interrupt from the system (see section\ \@ref(impl:ipi)).

```{.go #lst:sysrun caption="Running the system until completion" float=!ht}
// system/system.go
func (s *System) Run() {
    s.Start()
    s.WaitHalt() // = s.wgRunning.Wait()
    s.Stop()
}

func (s *System) Stop() {
    s.RaiseInterrupt(0, 1) // (coreID, fromID)
    s.WaitStop()           // = s.wgAwake.Wait()
}
```

We imagine most tests/examples will be workloads that eventually run to completion.
Thus, the cores should `Halt` when they don't have any more work to do and the system will eventually 
