## Memory controller

The memory controller manages access to memory.
Figure\ \@ref(fig:04-core) shows that the memory controller controls the caches and the TLB.

### Cache

All caches are implemented as fixed-size hash-maps with quadratic probing and a limited probing depth.
Hashing is naively implemented as a modulo of the indexing value.
This means that for each cache-line, there is a limited number of slots where it can be stored.
If all candidate slots are occupied when a cache-line needs to be stored, they are flushed back to main memory (if dirty), invalidated, and the new cache-line is loaded at the first of the candidate slots.

The custom hash-map performs significantly better than Go's own `map` type with the disadvantage that the number of entries is limited and there are only a certain number of slots available for each item (depending on the probe depth).
This might lead to excessive invalidation if processes have unexpected access patterns.
However, for "normal" usage -- where spatial and temporal locality applies -- cache performance should be more than adequate.

### TLB {#impl:tlb}

A similar hash-map implementation is used for the TLB as for the caches, though it has a separately configurable probe-depth and size.
